INSERT INTO USERS VALUES('user1','{noop}secret',TRUE);
INSERT INTO USERS VALUES('user2','{noop}secret',TRUE);
INSERT INTO USERS VALUES('user3','{noop}secret',TRUE);

INSERT INTO AUTHORITIES VALUES('user1','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('user2','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('user2','ROLE_EDITOR');
INSERT INTO AUTHORITIES VALUES('user3','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('user3','ROLE_ADMIN');