INSERT INTO USERS VALUES('user1','{noop}secret',TRUE);
INSERT INTO USERS VALUES('user2','{noop}secret',TRUE);
INSERT INTO USERS VALUES('user3','{noop}secret',TRUE);

INSERT INTO AUTHORITIES VALUES('user1','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('user2','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('user2','ROLE_EDITOR');
INSERT INTO AUTHORITIES VALUES('user3','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('user3','ROLE_ADMIN');

INSERT INTO T_NOTE(HEADER,BODY,USERNAME,CATEGORY) VALUES ('FIRST HEADER', 'FIRST BODY','user1','danger');
INSERT INTO T_NOTE(HEADER,BODY,USERNAME,CATEGORY) VALUES ('SECOND HEADER', '2 BODY','user1','danger');
INSERT INTO T_NOTE(HEADER,BODY,USERNAME,CATEGORY) VALUES ('3 HEADER', '3 BODY','user1','warning');
INSERT INTO T_NOTE(HEADER,BODY,USERNAME,CATEGORY) VALUES ('4 HEADER', '4 BODY','user2','succes');
INSERT INTO T_NOTE(HEADER,BODY,USERNAME,CATEGORY) VALUES ('5 HEADER', '5 BODY','user2','danger');
INSERT INTO T_NOTE(HEADER,BODY,USERNAME,CATEGORY) VALUES ('6 HEADER', '6 BODY','user2','info');
INSERT INTO T_NOTE(HEADER,BODY,USERNAME,CATEGORY) VALUES ('7 HEADER', '7 BODY','user2','warning');